### PR TITLE
feat: 🎸 Update Discord Link

### PR DESCRIPTION
**Pull request by brunoromeiro**
Set new Discord Link

### CODE REVIEW

**Comment by SuyashSonawane** [comment]
There are some guidelines that everyone should follow while contributing to this opensource project. While working in large teams, it is necessary to follow these steps to avoid any conflicts in the code and continue a smooth flow of collaboration amongst the developers.

Unfortunately, we will have to mark this PR invalid.

**Comment by pranavmittal611** [comment]
Just out of curiosity, why was this PR marked invalid?

**Comment by brunoromeiro** [comment]
I ended up not changing in both places, and I believe their approval for me to work on this issue was missing.

**Comment by brunoromeiro** [comment]
@SuyashSonawane That's it?

**Comment by tejasmorkar** [comment]
> Just out of curiosity, why was this PR marked invalid?

According to the Contribution guidelines, you must first reply to the issues and wait for an approval from the maintainers before making a PR or before working on it.

**Comment by brunoromeiro** [comment]
@tejasmorkar I am waiting for an answer within the issue to reopen the PR.

**Pull request closed without merging**
