### PR TITLE
Feature: Update Discord Invite Link

### PR DESCRIPTION
**Pull request by brunoromeiro**
Discord links have been updated

Issue #31

### CODE REVIEW

**Review by tejasmorkar — APPROVED** [review]
Awesome... Thank you for your contribution! 👍

**Comment by brunoromeiro** [comment]
Hi @tejasmorkar can you include the label '' hacktoberfest-accepted "in this PR? Thanks!
Because of this [Hacktoberfest Update](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by tejasmorkar** [comment]
> Hi @tejasmorkar can you include the label '' hacktoberfest-accepted "in this PR? Thanks!
> Because of this [Hacktoberfest Update](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

Hi @brunoromeiro,

We have gone through all the rules and updates from Hacktoberfest 2020. Our repository has the `hacktoberfest` topic and your PR was merged after approval, so there is no need for a `hacktoberfest-accepted` label on the PR. 

I've included the rules below for your reference from [https://hacktoberfest.digitalocean.com/hacktoberfest-update](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

```
PRs count if:
Submitted during the month of October AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)
```

**Comment by brunoromeiro** [comment]
@tejasmorkar thanks my friend!

**Pull request merged**
